### ISSUE TITLE
Using alt and title attribute

### ISSUE THREAD

**Issue by marionava** [artpolikarpov/fotorama#439] opened 2015-11-04 20:55 UTC
Only for SEO, it would be great if fotorama respect the title and alt attributes. I put it them but the fotorama script cut them off.

**Comment by sashamjolnir** [comment] 2015-11-05 18:13
++++++++++++++

**Comment by guz-anton** [comment] 2015-11-05 19:50
From SEO prospective if you place attributes on the page it's enough for crawler catch them. It doesn't matter what some js does on the page after load. Crawler will get full version of code.

So why do need fotorama might support `alt` and `title` attributes?

**Comment by AlikDex** [comment] 2016-02-17 16:30
Step one:
Open file fotorama.dev.js and search this string: 
`frameData.state = '';`
add the following line:
```
if ( frameData.data.hasOwnProperty('alt') ) {
 img.alt= frameData.data.alt;
 }
 if ( frameData.data.hasOwnProperty('title') ) {
 img.title= frameData.data.title;
 }
```
Step two:
Search string:
`height = numberFromMeasure(imgData.height || $img.attr('height'));`
And replace it:
```
height = numberFromMeasure(imgData.height || $img.attr('height')),
 alt = $img.attr('alt'),
 title = $img.attr('title');
 if (alt){
 $.extend(imgData, {
 alt: alt
  });
  }
  if (title){
  $.extend(imgData, {
  title: title
  });
  }
```
Step three:
Minify and rename file to fotorama.js
tested in 4.6.4 version.
P.S. sorry for my English =)

**Comment by emision** [comment] 2016-08-23 10:11
in my case it did not work as described above.
But i change second block of code 
` height = numberFromMeasure(imgData.height || $img.attr('height')),
                alt = $child.attr('alt'),
                title = $child.attr('alt');
            if (alt){
                $.extend(imgData, {
                    alt: alt
                });
            }
            if (title){
                $.extend(imgData, {
                    title: title
                });
            }`

This is very strange, but `$img` - is object of `<a>` tag, but `$child` is `<img>`

**Comment by Jakeroid** [comment] 2017-03-02 15:47
I don't understand why author can't add support for alt and title attributes. I will make fork of fotorama just for add alt and title attrs. Maybe after this author will make needed changes.

**Comment by kurraz-soft** [comment] 2018-10-11 09:51
My version
```
height = numberFromMeasure(imgData.height || $img.attr('height')),
    alt    = $child.context.alt,
    title  = $child.context.title;

    if (alt)   { $.extend(imgData, { alt: alt }); }
    if (title) { $.extend(imgData, { title: title }); }
```

**Comment by artpolikarpov** [comment] 2019-09-03 17:33
Closing this as duplicate of #329

**Closed by artpolikarpov** 2019-09-03 17:33 UTC
Labels: enhancement
