### ISSUE TITLE
Next and Previous Cache: Ability to load All images if desired (for seo)

### ISSUE THREAD

**Issue by joebordo** [artpolikarpov/fotorama#544] opened 2019-02-25 14:49 UTC
Fotorama by default has a next and previous cache. So it only loads the next and preview images in the html.

When the page loads only 3 images are loaded.

It would be nice to have a option, if the user wants to load all images.

**Comment by artpolikarpov** [comment] 2019-09-03 17:39
Duplicate of #538

**Closed by artpolikarpov** 2019-09-03 17:39 UTC
Labels: question
