### ISSUE TITLE
Fotorama Fullscreen: Pinch Zoom is really bad.

### ISSUE THREAD

**Issue by joebordo** [artpolikarpov/fotorama#543] opened 2019-02-25 14:45 UTC
I had to disable the full screen in magento 2 on mobile because of the pinch zoom behaviour.
It's really hard to use.

I think this is the most important thing to work on.

**Comment by artpolikarpov** [comment] 2019-08-30 15:47
Agree.

**Comment by artpolikarpov** [comment] 2019-09-03 17:19
Duplicate of #313

**Closed by artpolikarpov** 2019-09-03 17:19 UTC
Labels: enhancement
